version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: "@cycle/history"
    versions:
    - 8.0.0
